apiVersion: v1
kind: ConfigMap
metadata:
  name: repository-warehouse-nginx-conf
data:
  nginx.conf: |
    user nginx;
    worker_processes  3;
    error_log  /var/log/nginx/error.log;
    events {
      worker_connections  10240;
    }
    http {
      log_format  main
              'remote_addr:$remote_addr\t'
              'time_local:$time_local\t'
              'method:$request_method\t'
              'uri:$request_uri\t'
              'host:$host\t'
              'status:$status\t'
              'bytes_sent:$body_bytes_sent\t'
              'referer:$http_referer\t'
              'useragent:$http_user_agent\t'
              'forwardedfor:$http_x_forwarded_for\t'
              'request_time:$request_time';
      access_log    /var/log/nginx/access.log main;
      server {
          listen       80;
          root /repository-warehouse;
          location / {
          }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: repository-warehouse
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: repository-warehouse
  template:
    metadata:
      labels:
        app: repository-warehouse
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - name: nginx-conf-volume
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
            readOnly: true
          - mountPath: /var/log/nginx
            name: log
          - mountPath: /repository-warehouse
            name: repository-warehouse-volume
      volumes:
      - name: nginx-conf-volume
        configMap:
          name: repository-warehouse-nginx-conf
          items:
            - key: nginx.conf
              path: nginx.conf
      - name: log
        emptyDir: {}
      - name: repository-warehouse-volume
        nfs:
          server: 192.168.2.4
          path: /export/cr_cache
---
apiVersion: v1
kind: Service
metadata:
  name: repository-warehouse-nginx
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: repository-warehouse